### ISSUE TITLE
Not Displaying Creation Date Anymore....

### ISSUE THREAD

**Issue by garrettmac** [NeekSandhu/Repo-creation-date-checker-for-Github#1]
This did display the creation date initially, however now it's not. Not sure if it was a Github.com site update or what. 

Are you still getting it work in your browser?

**Comment by garrettmac** [comment]
Great work by the way, very useful!
Im running **Google Chrome 57.0.2987.133 (Official Build) (64-bit)** btw

**Comment by zikaari** [comment]
Works for me, can you try re-installing the extension. Also it doesn't work when you navigate within GitHub as GitHub uses pJax (like an SPA), so extension script is only injected on a true page-load.

**Comment by garrettmac** [comment]
idk what the deal was but its working now. I think it clashed with this extension https://github.com/sindresorhus/refined-github hiding it from me. Thanks for the response

**Comment by zikaari** [comment]
Thank you for pointing that extension out. I might just send them a PR with the same feature.
