### ISSUE TITLE
Firefox addon

### ISSUE THREAD

**Issue by evpix** [NeekSandhu/Repo-creation-date-checker-for-Github#4]
This addon would be useful in Firefox.

**Comment by zikaari** [comment]
Sorry for the missed reply there mate. But I no longer maintain this package, however I highly suggest you install [Refined Github](https://github.com/sindresorhus/refined-github) which includes the features this extension provides.
![image](https://user-images.githubusercontent.com/11316020/81487882-f07ed080-9216-11ea-8f8e-1e53b9313d76.png)

**Comment by evpix** [comment]
> 
> 
> Sorry for the missed reply there mate. But I no longer maintain this package, however I highly suggest you install [Refined Github](https://github.com/sindresorhus/refined-github)0 which includes the features this extension provides.
> ![image](https://user-images.githubusercontent.com/11316020/81487882-f07ed080-9216-11ea-8f8e-1e53b9313d76.png)

Thanks for the answer. I am very grateful for your help.
